import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ConvexClientProvider } from "./ConvexClientProvider";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const raleway=Raleway({subsets:["latin"]})
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <ClerkProvider>
     <html lang="en">
        <body className={raleway.className}>
             <ConvexClientProvider>
               {children}
             </ConvexClientProvider>
        </body>
      </html>
      </ClerkProvider>
  );
}
